/*
  CLASS: A CLASS IS A BLUEPRINT OR TEMPLATE THAT DEFINES THE 
  PROPERTIES (ATTRIBUTES) AND BEHAVIORS (METHODS) THAT THE
  OBJECTS CREATED FROM THE CLASS WILL HAVE.

  SYNTAX:
   accessmodifier class classname
   {
      
   }

  SYNTAX FOR OBJECT CREATION:
   classname objectname=new classname();

  
   ENCAPSULATION:
      THE PACKING OF BOTH VARIABLES AND METHODS IS CALLED AS 
      ENCAPSULATION
 */