/*
  WHAT IS PACKAGE:
  PACKAGE IS A CONTAINER WHICH CAN SEGREGATE 
  THE JAVA SOURCE FILES IN THE JAVA PROJECT

  THE NEED FOR A PACKAGE IN A PROJECT:
  1)IF YOU HAVE TWO FILES WITH THE SAME NAME 
  (E.G., UTILS.PY), PLACING THEM IN DIFFERENT 
  PACKAGES (E.G., PROJECTA/UTILS.PY AND PROJECTB/UTILS.PY) 
  ALLOWS YOU TO REFERENCE THEM WITHOUT AMBIGUITY. 

  2)USING PACKAGES IN JAVA WHEN YOU HAVE A LARGE NUMBER 
  OF FILES (LIKE 10,000) IS ESSENTIAL FOR ORGANIZATION: PACKAGES
  HELP YOU CATEGORIZE RELATED CLASSES AND INTERFACES, MAKING IT
  EASIER TO NAVIGATE THROUGH YOUR PROJECT. FOR EXAMPLE, YOU CAN 
  HAVE PACKAGES FOR DIFFERENT MODULES LIKE COM.COMPANYNAME.MODULEA 
  AND COM.COMPANYNAME.MODULEB.

  SYNTAC:
  THERE IS A FILE(example.java) AND I 
  WANT TO KEEP IT IN FOLDER(Srinivas)

  package Srinivas;
  _______________________________________


  FOLDER(Srinivas)->example1.java
  FOLDER(Arjun)->example2.java
  NOW I WANT TO USE example1.java FILE class in example2.java 
  THEN IMPORT IT INTO THIS 
 */